config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'main#home'

  resources :products

  resources :purchases do
    member do
      post 'register_sale'
      get 'download'
      get 'preview'
    end
  end

  resources :purchase_items, only: [:create, :update, :destroy]
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def purchase
    @purchase = Purchase.find(params[:id])
  end

  def show
    @purchase = Purchase.find(params[:id])
  end

  def register_sale
    @purchase = current_user.current_purchase

    if @purchase.update(active: true)
      redirect_to purchase_path(@purchase), notice: 'Sale registered successfully.'
    else
      redirect_to products_path, alert: 'Failed to register sale.'
    end
  end

  def download
    pdf = generate_pdf

    send_data(pdf.render,
              filename: "purchase_#{purchase.updated_at.strftime("%d/%m/%Y %H:%M")}.pdf",
              type: "application/pdf")
  end

  def preview
    pdf = generate_pdf

    send_data(pdf.render,
              filename: "purchase_#{purchase.updated_at.strftime("%d/%m/%Y %H:%M")}.pdf",
              type: "application/pdf",
              disposition: "inline")
  end

  private

  def generate_pdf
    pdf = Prawn::Document.new

    pdf.text "Your Purchase made on #{purchase.updated_at.strftime("%d/%m/%Y %H:%M")}", size:  20, style: :bold
    purchase.purchase_items.each do |item|
      pdf.text "* #{item.product.name} - #{item.quantity} items - $#{item.total_price.to_f.round(2)}"
    end

    pdf.text "Total Price: #{purchase.total_price.to_f.round(2)}"

    pdf
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/show.html.erb
<div class="container mt-4">
  <h1>Purchase Details</h1>

  <div>
    <% if @purchase.active? %>
      <p><strong>Date:</strong> <%= @purchase.updated_at %></p>
    <% end %>
    <p><strong>Total Price:</strong> $<%= @purchase.total_price %></p>
  </div>

  <% if @purchase.active? %>
    <h2>Purchased Items</h2>
  <% else %>
    <h2>Added Items</h2>
  <% end %>

  <% if @purchase.purchase_items.any? %>
    <table class="table table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>Product</th>
          <th>Quantity</th>
          <th>Subtotal</th>
        </tr>
      </thead>
      <tbody>
        <% @purchase.purchase_items.each do |purchase_item| %>
          <tr>
            <td><%= purchase_item.product.name %></td>
            <td><%= purchase_item.quantity %></td>
            <td>$<%= purchase_item.total_price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No items in this purchase.</p>
  <% end %>

  <div class="mt-3">
    <%= link_to "Download", download_purchase_path(purchase_id: @purchase.id), class: "btn btn-primary" %>
    <%= link_to "Preview", preview_purchase_path(purchase_id: @purchase.id), class: "btn btn-secondary" %>
  </div>
</div>