config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'main#home'

  resources :products

  resources :purchases do
    member do
      post 'register_sale'
      get 'download'
      get 'preview'
    end
  end

  resources :purchase_items, only: [:create, :update, :destroy]
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :purchase_items
  has_many :purchases, through: :purchase_items

  has_one_attached :image

  def units_sold
    purchase_items.joins(:purchase).where(purchases: { active: true }).sum(:quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = if params[:search].present?
                  Product.where("name LIKE ?", "%#{params[:search]}%")
                else
                  Product.all
                end
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to root_path, notice: 'Product was successfully created.'
    else
      render 'new'
    end
  end

  def new
    @product = Product.new
  end

  def update
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :image)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<%= turbo_frame_tag "product_#{product.id}" do %>
  <div class="col-md-3">
    <div class="card text-bg-dark mb-3" style="width: 12rem; height: 21rem; margin: 0.2rem;">
     <% quantity_on_list = current_user.current_purchase.find_quantity_from_item(product) %>
      <%= link_to "/products/#{product.id}", data: { turbo_frame: "product_#{product.id}" } do %>
        <%= turbo_frame_tag "product_image_#{product.id}" do %>
          <% if product.image.attached? %>
            <%= image_tag product.image, class: "card-img-top", alt: product.name, width: 100, height: 150 %>
          <% else %>
            <p class="text-center">No image available</p>
          <% end %>
        <% end %>
      <% end %>
      <div class="card-body d-flex flex-column">
        <h6 class="card-title"> <%= product.name %>
        </h6>
         <% if quantity_on_list > 0 %>
            <span class="text-success fw-bold mt-auto"> ( <%= quantity_on_list %> Added )</span>
            <%= button_to 'Remove', purchase_item_path(current_user.current_purchase.purchase_items.find_by(product: product)), method: :delete, remote: true, class: 'btn btn-danger btn-sm' %>
          <% end %>
        <p class="card-text"> $ <%= product.price %></p>

        <%= form_for product.purchase_items.new, url: purchase_items_path, method: :post, remote: true, html: { id: "purchase_item_form_#{product.id}" } do |f| %>
          <%= f.hidden_field :product_id, value: product.id %>
          <div class="input-group mb-3">
            <%= f.number_field :quantity, value: 0, class: 'form-control purchase-item-quantity', min: 1 %>
            <div class="input-group-append">
              <%= f.submit '+', class: 'btn btn-outline-secondary add-button', id: "addButton_#{product.id}" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/products/index.html.erb
<h3 class="text-primary">Catalog</h3>
<br>
<div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-1">
  <% @products.each do |product| %>
   <%= render partial: 'products/product', locals: { product: product } %>
  <% end %>
</div>

<%= render "layouts/bottombar" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_with model: @product do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price, step: 'any' %>
  </div>

  <div>
    <%= form.label :image%>
    <%= form.file_field :image%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8">
      <h1><%= @product.name %></h1>
      <p class="lead"><%= @product.description %></p>
      <h3 class="fw-bold">$<%= @product.price %></h3>
    </div>
    <div class="col-md-4">
      <% if @product.image.attached? %>
        <%= image_tag @product.image, class: "img-fluid", alt: @product.name %>
      <% else %>
        <p class="text-center">No image available</p>
      <% end %>
    </div>
  </div>
</div>