config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'main#home'

  resources :products

  resources :purchases do
    member do
      post 'register_sale'
      get 'download'
      get 'preview'
    end
  end

  resources :purchase_items, only: [:create, :update, :destroy]
end

app/views/layouts/_bottombar.html.erb
<nav class="navbar fixed-bottom bg-primary bg-body-tertiary" data-bs-theme="dark">
    <%= link_to 'Check list of items', purchase_path(current_user.current_purchase), class: 'btn btn-primary ms-3' %>
    <div class="ms-auto d-flex align-items-center">
         <%= button_to 'Register Sale', register_sale_purchase_path(current_user.current_purchase), method: :post, class: 'btn btn-success me-3' %>
        <%= turbo_frame_tag "total_price" do %>
        <span class="navbar-brand mb-0 h1">Total $ <%= current_user.current_purchase.total_price %> </span>
        <% end %>
    </div>
</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Little Bee</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% unless current_page?(products_path) %>
        <li class="nav-item">
          <%= link_to "Register a sale", products_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
      <% if current_page?(products_path) %>
        <form class="d-flex" role="search" method="get" action="<%= products_path %>">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      <% end %>
      <ul class="navbar-nav">
         <% if current_user %>
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_total_price.html.erb
<span class="navbar-brand mb-0 h1">Total $ <%= purchase.total_price %> </span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LittleBee</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
     <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>